paths:
  raw_data: data/raw/
  processed_data: data/processed/
  eda: notebooks/notebooks/exploratory - Verdandi
  models: models/
  forecasts: forecasts/
  reports: reports/figures/

data:
  target_col: 'Load'
  datetime_col: 'Datetime'

model:
  random_state: 42
  test_size: 0.2
